tasks:
  - name: Python Requirements
    command: pip install -r /workspace/tendermint_demo/requirements.txt 
vscode:
  extensions:
    - GitHub.vscode-pull-request-github
    - ms-python.python
    - ms-azuretools.vscode-docker